name: Mutliple-OS-Matrix
on: 
    workflow_dispatch:
        
    push:
        branches: [main]

jobs:
    system-info:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - name: Print OS
              run: echo "The operating System: ${{ matrix.os }}"

            - name: Print Hostname
              run: hostname

            - name: Print User
            - run: whoami
