name: Multiple-OS
on:
    push:
    branches: [main]
    workflow_dispatch:

jobs:
    Multi-runner-jobs:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}

steps: 
  - name: checkout-code
    uses: actions/checkout@v4
    
  - name: Print OS 
    run: echo "Operation Sytem : ${{ matrix.os }}

  - name: Print hostname
    run: hostname

  - name: Print Current User
    run: whoami

    
    
