name: hello worksflow
on:
    push:
        branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: checkout-code
      uses: actions/checkout@v4
    - name: print greeting
      run: echo "Hello from GitHub Actions!"
    - name: Print current date and time
      run: date "+%y-%m-%d %H:%M:%S"
    - name: print branch
      run: echo "Branch name is ${{github.ref_name}}"
    - name: Repo name 
      run: echo " Repo name: ${{ github.repository }}"
  
    
