name: mannual deploy
on:
  workflow_dispatch:
      input:
        environment: 
        description: "Select The Environment"
        required: true
        defualt: "stagging"  
        type: choice
        option:
        - Production
        - Stagging
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Print selected environment
          run: echo "Deploying to environment: ${{ github.event.inputs.environment }}"

