name: Schedule_Trigger
on:
    schedule:
        - cron:  '0 0 * * *'

jobs:
    run-task:
      runs-on: ubuntu-latest
      steps:
          - name: checkout-code
            uses: actions/checkout@v4
            
          - name: Execute scheduled task
            run: echo ""This job runs daily at midnight UTC"" 

