name: Self-Hosted-Runner

on: 
    workflow_dispatch:

jobs:
    self-hosted-EC2:
        runs-on: self-hosted

        steps:
            - name: Create folder in EC2
              run: touch devops
        
